# Descripcipción del proyecto

Film Junky Union, una nueva comunidad vanguardista para los aficionados de las películas clásicas, está desarrollando un sistema para filtrar y categorizar reseñas de películas. Tu objetivo es entrenar un modelo para detectar las críticas negativas de forma automática. Para lograrlo, utilizarás un conjunto de datos de reseñas de películas de IMDB con leyendas de polaridad para construir un modelo para clasificar las reseñas positivas y negativas. Este deberá alcanzar un valor F1 de al menos 0.85.

## Inicialización

In [6]:
import math

import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

from tqdm.auto import tqdm

In [7]:
%matplotlib inline
%config InlineBackend.figure_format = 'png'
# la siguiente línea proporciona gráficos de mejor calidad en pantallas HiDPI
# %config InlineBackend.figure_format = 'retina'

In [8]:
# esto es para usar progress_apply, puedes leer más en https://pypi.org/project/tqdm/#pandas-integration
tqdm.pandas()

## Cargar datos

In [10]:
df_reviews = pd.read_csv('imdb_reviews.tsv', sep='\t', dtype={'votes': 'Int64'})
df_reviews.sample(5)

,tconst,title_type,primary_title,original_title,start_year,end_year,runtime_minutes,is_adult,genres,average_rating,votes,review,rating,sp,pos,ds_part,idx
20433,tt0023139,movie,Life Begins,Life Begins,1932,\N,71,0,Drama,6.5,349,"Even in the 21st century, child-bearing is dan...",8,pos,1,train,5387
31294,tt0857265,movie,Sleuth,Sleuth,2007,\N,88,0,"Crime,Drama,Mystery",6.5,29981,"At the name of Pinter, every knee shall bow - ...",2,neg,0,train,4759
16444,tt0113305,movie,Higher Learning,Higher Learning,1995,\N,127,0,"Crime,Drama,Thriller",6.5,17621,Higher Learning says its OK for blacks to torm...,1,neg,0,train,2705
37946,tt0863080,tvMovie,The House Next Door,The House Next Door,2006,\N,86,0,"Horror,Mystery,Thriller",4.7,838,When I heard that this movie was coming out th...,7,pos,1,train,6643
14233,tt0274518,short,Gayniggers from Outer Space,Gayniggers from Outer Space,1992,\N,26,0,"Comedy,Sci-Fi,Short",5.9,5947,I was recently online looking at a site that f...,2,neg,0,train,6384

In [11]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47331 entries, 0 to 47330
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tconst           47331 non-null  object
 1   title_type       47331 non-null  object
 2   primary_title    47331 non-null  object
 3   original_title   47331 non-null  object
 4   start_year       47331 non-null  int64
 5   end_year         47331 non-null  object
 6   runtime_minutes  47331 non-null  object
 7   is_adult         47331 non-null  int64
 8   genres           47331 non-null  object
 9   average_rating   47329 non-null  float64
 10  votes            47329 non-null  Int64
 11  review           47331 non-null  object
 12  rating           47331 non-null  int64
 13  sp               47331 non-null  object
 14  pos              47331 non-null  int64
 15  ds_part          47331 non-null  object
 16  idx              47331 non-null  int64
dtypes: Int64(1), float64(1), int64(5), object(10)
memory usage: 6.2+ MB

## EDA

Veamos el número de películas y reseñas a lo largo de los años.

In [19]:
fig, axs = plt.subplots(2, 1, figsize=(16, 8))

ax = axs[0]

dft1 = df_reviews[['tconst', 'start_year']].drop_duplicates() \
    ['start_year'].value_counts().sort_index()
dft1 = dft1.reindex(index=np.arange(dft1.index.min(), max(dft1.index.max(), 2021))).fillna(0)
dft1.plot(kind='bar', ax=ax)
ax.set_title('Número de películas a lo largo de los años')

ax = axs[1]

dft2 = df_reviews.groupby(['start_year', 'pos'])['pos'].count().unstack()
dft2 = dft2.reindex(index=np.arange(dft2.index.min(), max(dft2.index.max(), 2021))).fillna(0)

dft2.plot(kind='bar', stacked=True, label='#reviews (neg, pos)', ax=ax)

dft2 = df_reviews['start_year'].value_counts().sort_index()
dft2 = dft2.reindex(index=np.arange(dft2.index.min(), max(dft2.index.max(), 2021))).fillna(0)
dft3 = (dft2/dft1).fillna(0)
axt = ax.twinx()
dft3.reset_index(drop=True).rolling(5).mean().plot(color='orange', label='reviews per movie (avg over 5 years)', ax=axt)

lines, labels = axt.get_legend_handles_labels()
ax.legend(lines, labels, loc='upper left')

ax.set_title('Número de reseñas a lo largo de los años')

fig.tight_layout()

Veamos la distribución del número de reseñas por película con el conteo exacto y KDE (solo para saber cómo puede diferir del conteo exacto)

In [23]:
fig, axs = plt.subplots(1, 2, figsize=(16, 5))

ax = axs[0]
dft = df_reviews.groupby('tconst')['review'].count() \
    .value_counts() \
    .sort_index()
dft.plot.bar(ax=ax)
ax.set_title('Gráfico de barras de #Reseñas por película')

ax = axs[1]
dft = df_reviews.groupby('tconst')['review'].count()
sns.kdeplot(dft, ax=ax)
ax.set_title('Gráfico KDE de #Reseñas por película')

fig.tight_layout()

In [25]:
df_reviews['pos'].value_counts()

pos
0    23715
1    23616
Name: count, dtype: int64

In [26]:
fig, axs = plt.subplots(1, 2, figsize=(12, 4))

ax = axs[0]
dft = df_reviews.query('ds_part == "train"')['rating'].value_counts().sort_index()
dft = dft.reindex(index=np.arange(min(dft.index.min(), 1), max(dft.index.max(), 11))).fillna(0)
dft.plot.bar(ax=ax)
ax.set_ylim([0, 5000])
ax.set_title('El conjunto de entrenamiento: distribución de puntuaciones')

ax = axs[1]
dft = df_reviews.query('ds_part == "test"')['rating'].value_counts().sort_index()
dft = dft.reindex(index=np.arange(min(dft.index.min(), 1), max(dft.index.max(), 11))).fillna(0)
dft.plot.bar(ax=ax)
ax.set_ylim([0, 5000])
ax.set_title('El conjunto de prueba: distribución de puntuaciones')

fig.tight_layout()

Distribución de reseñas negativas y positivas a lo largo de los años para dos partes del conjunto de datos

In [29]:
fig, axs = plt.subplots(2, 2, figsize=(16, 8), gridspec_kw=dict(width_ratios=(2, 1), height_ratios=(1, 1)))

ax = axs[0][0]

dft = df_reviews.query('ds_part == "train"').groupby(['start_year', 'pos'])['pos'].count().unstack()
dft.index = dft.index.astype('int')
dft = dft.reindex(index=np.arange(dft.index.min(), max(dft.index.max(), 2020))).fillna(0)
dft.plot(kind='bar', stacked=True, ax=ax)
ax.set_title('El conjunto de entrenamiento: número de reseñas de diferentes polaridades por año')

ax = axs[0][1]

dft = df_reviews.query('ds_part == "train"').groupby(['tconst', 'pos'])['pos'].count().unstack()
sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)
ax.legend()
ax.set_title('El conjunto de entrenamiento: distribución de diferentes polaridades por película')

ax = axs[1][0]

dft = df_reviews.query('ds_part == "test"').groupby(['start_year', 'pos'])['pos'].count().unstack()
dft.index = dft.index.astype('int')
dft = dft.reindex(index=np.arange(dft.index.min(), max(dft.index.max(), 2020))).fillna(0)
dft.plot(kind='bar', stacked=True, ax=ax)
ax.set_title('El conjunto de prueba: número de reseñas de diferentes polaridades por año')

ax = axs[1][1]

dft = df_reviews.query('ds_part == "test"').groupby(['tconst', 'pos'])['pos'].count().unstack()
sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)
ax.legend()
ax.set_title('El conjunto de prueba: distribución de diferentes polaridades por película')

fig.tight_layout()

C:\Users\pirom\AppData\Local\Temp\ipykernel_21176\1324160450.py:14: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
C:\Users\pirom\AppData\Local\Temp\ipykernel_21176\1324160450.py:15: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)
C:\Users\pirom\AppData\Local\Temp\ipykernel_21176\1324160450.py:30: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
C:\Users\pirom\AppData\Local\Temp\ipykernel_21176\1324160450.py:31: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)

## Procedimiento de evaluación

Composición de una rutina de evaluación que se pueda usar para todos los modelos en este proyecto

In [37]:
import sklearn.metrics as metrics
def evaluate_model(model, train_features, train_target, test_features, test_target):

    eval_stats = {}

    fig, axs = plt.subplots(1, 3, figsize=(20, 6))

    for type, features, target in (('train', train_features, train_target), ('test', test_features, test_target)):

        eval_stats[type] = {}

        pred_target = model.predict(features)
        pred_proba = model.predict_proba(features)[:, 1]

        # F1
        f1_thresholds = np.arange(0, 1.01, 0.05)
        f1_scores = [metrics.f1_score(target, pred_proba>=threshold) for threshold in f1_thresholds]

        # ROC
        fpr, tpr, roc_thresholds = metrics.roc_curve(target, pred_proba)
        roc_auc = metrics.roc_auc_score(target, pred_proba)
        eval_stats[type]['ROC AUC'] = roc_auc

        # PRC
        precision, recall, pr_thresholds = metrics.precision_recall_curve(target, pred_proba)
        aps = metrics.average_precision_score(target, pred_proba)
        eval_stats[type]['APS'] = aps

        if type == 'train':
            color = 'blue'
        else:
            color = 'green'

        # Valor F1
        ax = axs[0]
        max_f1_score_idx = np.argmax(f1_scores)
        ax.plot(f1_thresholds, f1_scores, color=color, label=f'{type}, max={f1_scores[max_f1_score_idx]:.2f} @ {f1_thresholds[max_f1_score_idx]:.2f}')
        # establecer cruces para algunos umbrales
        for threshold in (0.2, 0.4, 0.5, 0.6, 0.8):
            closest_value_idx = np.argmin(np.abs(f1_thresholds-threshold))
            marker_color = 'orange' if threshold != 0.5 else 'red'
            ax.plot(f1_thresholds[closest_value_idx], f1_scores[closest_value_idx], color=marker_color, marker='X', markersize=7)
        ax.set_xlim([-0.02, 1.02])
        ax.set_ylim([-0.02, 1.02])
        ax.set_xlabel('threshold')
        ax.set_ylabel('F1')
        ax.legend(loc='lower center')
        ax.set_title(f'Valor F1')

        # ROC
        ax = axs[1]
        ax.plot(fpr, tpr, color=color, label=f'{type}, ROC AUC={roc_auc:.2f}')
        # establecer cruces para algunos umbrales
        for threshold in (0.2, 0.4, 0.5, 0.6, 0.8):
            closest_value_idx = np.argmin(np.abs(roc_thresholds-threshold))
            marker_color = 'orange' if threshold != 0.5 else 'red'
            ax.plot(fpr[closest_value_idx], tpr[closest_value_idx], color=marker_color, marker='X', markersize=7)
        ax.plot([0, 1], [0, 1], color='grey', linestyle='--')
        ax.set_xlim([-0.02, 1.02])
        ax.set_ylim([-0.02, 1.02])
        ax.set_xlabel('FPR')
        ax.set_ylabel('TPR')
        ax.legend(loc='lower center')
        ax.set_title(f'Curva ROC')

        # PRC
        ax = axs[2]
        ax.plot(recall, precision, color=color, label=f'{type}, AP={aps:.2f}')
        # establecer cruces para algunos umbrales
        for threshold in (0.2, 0.4, 0.5, 0.6, 0.8):
            closest_value_idx = np.argmin(np.abs(pr_thresholds-threshold))
            marker_color = 'orange' if threshold != 0.5 else 'red'
            ax.plot(recall[closest_value_idx], precision[closest_value_idx], color=marker_color, marker='X', markersize=7)
        ax.set_xlim([-0.02, 1.02])
        ax.set_ylim([-0.02, 1.02])
        ax.set_xlabel('recall')
        ax.set_ylabel('precision')
        ax.legend(loc='lower center')
        ax.set_title(f'PRC')

        eval_stats[type]['Accuracy'] = metrics.accuracy_score(target, pred_target)
        eval_stats[type]['F1'] = metrics.f1_score(target, pred_target)

    df_eval_stats = pd.DataFrame(eval_stats)
    df_eval_stats = df_eval_stats.round(2)
    df_eval_stats = df_eval_stats.reindex(index=('Accuracy', 'F1', 'APS', 'ROC AUC'))

    print(df_eval_stats)

    return

## Normalización

Suponemos que todos los modelos a continuación aceptan textos en minúsculas y sin dígitos, signos de puntuación, etc.

In [40]:
import re
import string
import spacy
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

In [41]:
import re
def normalize_text(text):
    text = re.sub("[^a-zA-Z]", " ", text).lower()
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [42]:
df_reviews['review_norm'] = df_reviews['review'].apply(normalize_text)

## División entrenamiento / prueba

Por fortuna, todo el conjunto de datos ya está dividido en partes de entrenamiento/prueba; 'ds_part' es el indicador correspondiente.

In [47]:
df_reviews_train = df_reviews.query('ds_part == "train"').copy()
df_reviews_test = df_reviews.query('ds_part == "test"').copy()

train_target = df_reviews_train['pos']
test_target = df_reviews_test['pos']

print(df_reviews_train.shape)
print(df_reviews_test.shape)

(23796, 18)
(23535, 18)

## Trabajar con modelos

### Modelo 0 - Constante

In [50]:
from sklearn.dummy import DummyClassifier

In [54]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

from nltk.corpus import stopwords as nltk_stopwords

In [55]:
stop_words = nltk_stopwords.words('english')
count_tf_idf = TfidfVectorizer(  
    stop_words=list(stop_words))

In [58]:
train_corpus = df_reviews_train['review_norm']
test_corpus = df_reviews_test['review_norm']

In [60]:
features_train_1 = count_tf_idf.fit_transform(train_corpus)
features_test_1 = count_tf_idf.transform(test_corpus)

In [61]:
dummy_model = DummyClassifier(strategy='most_frequent')
dummy_model.fit(features_train_1, train_target)

DummyClassifier(strategy='most_frequent')

In [62]:
dummy_predictions = dummy_model.predict(df_reviews_test)

In [80]:
evaluate_model(dummy_model, df_reviews_train, train_target, df_reviews_test, test_target)

          train  test
Accuracy    0.5   0.5
F1          0.0   0.0
APS         0.5   0.5
ROC AUC     0.5   0.5

### Modelo 1 - NLTK, TF-IDF y LR

TF-IDF

In [123]:
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [125]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [127]:
def preprocess_text(text):
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word.isalpha()]
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    
    return " ".join(tokens)

In [129]:
count_tf_idf = TfidfVectorizer()

In [131]:
train_corpus = df_reviews_train['review'].apply(preprocess_text)
test_corpus = df_reviews_test['review'].apply(preprocess_text)

In [132]:
features_train_1 = count_tf_idf.fit_transform(train_corpus)
features_test_1 = count_tf_idf.transform(test_corpus)

In [133]:
y_train  =  df_reviews_train['pos']
y_test  =  df_reviews_test['pos']

In [134]:

model_1 = LogisticRegression()
model_1.fit(features_train_1, y_train)

LogisticRegression()

In [135]:
evaluate_model(model_1, features_train_1, y_train, features_test_1, y_test)

          train  test
Accuracy   0.93  0.88
F1         0.93  0.88
APS        0.98  0.95
ROC AUC    0.98  0.95

### Modelo 3 - spaCy, TF-IDF y LR

In [81]:
import spacy

nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

In [83]:
def text_preprocessing_3(text):
    doc=nlp(text.lower())
    lemmas=[token.lemma_ for token in doc]
    
    # Remover espacios extra
    lemmas = ' '.join(lemmas)
    
    return lemmas

In [85]:
df_reviews['review_procesing'] = df_reviews['review'].apply(text_preprocessing_3)

In [89]:
df_reviews_train = df_reviews.query('ds_part == "train"').copy()
df_reviews_test = df_reviews.query('ds_part == "test"').copy()

train_corpus = df_reviews_train['review_procesing']
test_corpus = df_reviews_test['review_procesing']

In [91]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    min_df=5,
    stop_words=list(stop_words)
)

X_train = vectorizer.fit_transform(df_reviews_train['review_procesing'])
X_test = vectorizer.transform(df_reviews_test['review_procesing'])

In [92]:
y_train = df_reviews_train['pos']
y_test = df_reviews_test['pos']

In [93]:
model_spacy = LogisticRegression(max_iter=1000)
model_spacy.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [94]:
evaluate_model(model_spacy, X_train, y_train, X_test, y_test)

          train  test
Accuracy   0.93  0.88
F1         0.93  0.88
APS        0.98  0.95
ROC AUC    0.98  0.95

### Modelo 4 - spaCy, TF-IDF y LGBMClassifier

In [100]:

from lightgbm import LGBMClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

In [101]:
model_LGBM = LGBMClassifier(num_leaves=20,
    max_depth=10,
    learning_rate=0.05,
    n_estimators=200)

In [102]:


model_LGBM.fit(X_train, y_train)

C:\Users\pirom\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] El sistema no puede encontrar el archivo especificado
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\pirom\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\pirom\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pirom\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\pirom\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[LightGBM] [Info] Number of positive: 11884, number of negative: 11912
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.405880 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 546953
[LightGBM] [Info] Number of data points in the train set: 23796, number of used features: 9951
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499412 -> initscore=-0.002353
[LightGBM] [Info] Start training from score -0.002353

LGBMClassifier(learning_rate=0.05, max_depth=10, n_estimators=200,
               num_leaves=20)

In [103]:
evaluate_model(model_LGBM, X_train, y_train, X_test, y_test)

C:\Users\pirom\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\Users\pirom\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\Users\pirom\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\Users\pirom\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

          train  test
Accuracy   0.89  0.85
F1         0.89  0.85
APS        0.96  0.93
ROC AUC    0.96  0.93

###  Modelo 9 - BERT

In [106]:
import torch
import transformers

In [107]:
tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-uncased')
config = transformers.BertConfig.from_pretrained('bert-base-uncased')
model = transformers.BertModel.from_pretrained('bert-base-uncased')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [108]:
def BERT_text_to_embeddings(texts, max_length=512, batch_size=32, force_device=None, disable_progress_bar=False):

    if force_device is not None:
        device = torch.device(force_device)
    else:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    model.to(device)
    model.eval()

    if not disable_progress_bar:
        print(f'Uso del dispositivo {device}.')

    embeddings = []

    for i in tqdm(range(0, len(texts), batch_size), disable=disable_progress_bar):

        batch_texts = texts[i:i+batch_size]

        encoded = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            max_length=max_length,
            return_tensors="pt"
        )

        input_ids = encoded["input_ids"].to(device)
        attention_mask = encoded["attention_mask"].to(device)

        with torch.no_grad():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

        # CLS token embedding
        cls_embeddings = outputs.last_hidden_state[:, 0, :]
        embeddings.append(cls_embeddings.cpu().numpy())

    return np.vstack(embeddings)

In [129]:
# ¡Atención! La ejecución de BERT para miles de textos puede llevar mucho tiempo en la CPU, al menos varias horas
train_features_9 = BERT_text_to_embeddings(
    df_reviews_train['review_procesing'].astype(str).tolist()
)

Uso del dispositivo cuda.

  0%|          | 0/744 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
test_features_9 = BERT_text_to_embeddings(
    df_reviews_test['review_procesing'].astype(str).tolist()
)

In [ ]:
print(df_reviews_train['review_procesing'].shape)
print(train_features_9.shape)
print(test_features_9.shape)

In [184]:
# si ya obtuviste los insertados, te recomendamos guardarlos para tenerlos listos si
np.savez_compressed('features_9.npz', train_features_9=train_features_9, test_features_9=test_features_9)

# y cargar...
# with np.load('features_9.npz') as data:
#     train_features_9 = data['train_features_9']
#     test_features_9 = data['test_features_9']

In [144]:
data = np.load('features_9.npz')

train_features_9 = data['train_features_9']
test_features_9 = data['test_features_9']

In [146]:
model_9  = LogisticRegression()

In [148]:
model_9.fit(train_features_9,y_train)

C:\Users\pirom\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [150]:
evaluate_model(model_9, train_features_9, y_train, test_features_9, y_test)

          train  test
Accuracy   0.88  0.87
F1         0.88  0.87
APS        0.95  0.94
ROC AUC    0.95  0.94

## Mis reseñas

In [152]:
# puedes eliminar por completo estas reseñas y probar tus modelos en tus propias reseñas; las que se muestran a continuación son solo ejemplos

my_reviews = pd.DataFrame([
    'I did not simply like it, not my kind of movie.',
    'Well, I was bored and felt asleep in the middle of the movie.',
    'I was really fascinated with the movie',
    'Even the actors looked really old and disinterested, and they got paid to be in the movie. What a soulless cash grab.',
    'I didn\'t expect the reboot to be so good! Writers really cared about the source material',
    'The movie had its upsides and downsides, but I feel like overall it\'s a decent flick. I could see myself going to see it again.',
    'What a rotten attempt at a comedy. Not a single joke lands, everyone acts annoying and loud, even kids won\'t like this!',
    'Launching on Netflix was a brave move & I really appreciate being able to binge on episode after episode, of this exciting intelligent new drama.'
], columns=['review'])

"""
my_reviews = pd.DataFrame([
    'Simplemente no me gustó, no es mi tipo de película.',
    'Bueno, estaba aburrido y me quedé dormido a media película.',
    'Estaba realmente fascinada con la película',
    'Hasta los actores parecían muy viejos y desinteresados, y les pagaron por estar en la película. Qué robo tan desalmado.',
    '¡No esperaba que el relanzamiento fuera tan bueno! Los escritores realmente se preocuparon por el material original',
    'La película tuvo sus altibajos, pero siento que, en general, es una película decente. Sí la volvería a ver',
    'Qué pésimo intento de comedia. Ni una sola broma tiene sentido, todos actúan de forma irritante y ruidosa, ¡ni siquiera a los niños les gustará esto!',
    'Fue muy valiente el lanzamiento en Netflix y realmente aprecio poder seguir viendo episodio tras episodio de este nuevo drama tan emocionante e inteligente.'
], columns=['review'])
"""

my_reviews['review_norm'] = my_reviews['review'].apply(text_preprocessing_3)

my_reviews

,review,review_norm
0,"I did not simply like it, not my kind of movie.","I do not simply like it , not my kind of movie ."
1,"Well, I was bored and felt asleep in the middl...","well , I be bored and feel asleep in the middl..."
2,I was really fascinated with the movie,I be really fascinate with the movie
3,Even the actors looked really old and disinter...,even the actor look really old and disinterest...
4,I didn't expect the reboot to be so good! Writ...,I do not expect the reboot to be so good ! wri...
5,"The movie had its upsides and downsides, but I...","the movie have its upside and downside , but I..."
6,What a rotten attempt at a comedy. Not a singl...,what a rotten attempt at a comedy . not a sing...
7,Launching on Netflix was a brave move & I real...,launch on netflix be a brave move & I really a...

### Modelo 2

In [155]:
texts = my_reviews['review_norm']

my_reviews_pred_prob = model_1.predict_proba(count_tf_idf.transform(texts))[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.14:  I do not simply like it , not my kind of movie .
0.26:  well , I be bored and feel asleep in the middle of the movie .
0.49:  I be really fascinate with the movie
0.16:  even the actor look really old and disinterested , and they get pay to be in the movie . what a soul
0.28:  I do not expect the reboot to be so good ! writer really care about the source material
0.55:  the movie have its upside and downside , but I feel like overall it be a decent flick . I could see
0.03:  what a rotten attempt at a comedy . not a single joke land , everyone act annoying and loud , even k
0.82:  launch on netflix be a brave move & I really appreciate be able to binge on episode after episode ,

### Modelo 3

In [158]:
texts = my_reviews['review_norm'].fillna('').astype(str)

texts_processed = texts.apply(normalize_text)

X_my = vectorizer.transform(texts_processed)

my_reviews_pred_prob = model_spacy.predict_proba(X_my)[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.26:  I do not simply like it , not my kind of movie .
0.16:  well , I be bored and feel asleep in the middle of the movie .
0.59:  I be really fascinate with the movie
0.12:  even the actor look really old and disinterested , and they get pay to be in the movie . what a soul
0.16:  I do not expect the reboot to be so good ! writer really care about the source material
0.35:  the movie have its upside and downside , but I feel like overall it be a decent flick . I could see
0.04:  what a rotten attempt at a comedy . not a single joke land , everyone act annoying and loud , even k
0.94:  launch on netflix be a brave move & I really appreciate be able to binge on episode after episode ,

### Modelo 4

In [161]:
texts = my_reviews['review_norm']

tfidf_vectorizer_4 = vectorizer
my_reviews_pred_prob = model_LGBM.predict_proba(tfidf_vectorizer_4.transform(texts.apply(lambda x: text_preprocessing_3(x))))[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.63:  I do not simply like it , not my kind of movie .
0.61:  well , I be bored and feel asleep in the middle of the movie .
0.63:  I be really fascinate with the movie
0.52:  even the actor look really old and disinterested , and they get pay to be in the movie . what a soul
0.72:  I do not expect the reboot to be so good ! writer really care about the source material
0.65:  the movie have its upside and downside , but I feel like overall it be a decent flick . I could see
0.38:  what a rotten attempt at a comedy . not a single joke land , everyone act annoying and loud , even k
0.70:  launch on netflix be a brave move & I really appreciate be able to binge on episode after episode ,

C:\Users\pirom\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

### Modelo 9

In [164]:
texts = my_reviews['review_norm']
my_reviews_features_9 = BERT_text_to_embeddings(texts.tolist(), disable_progress_bar=True)

my_reviews_pred_prob = model_9.predict_proba(my_reviews_features_9)[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.51:  I do not simply like it , not my kind of movie .
0.00:  well , I be bored and feel asleep in the middle of the movie .
0.55:  I be really fascinate with the movie
0.01:  even the actor look really old and disinterested , and they get pay to be in the movie . what a soul
0.62:  I do not expect the reboot to be so good ! writer really care about the source material
0.94:  the movie have its upside and downside , but I feel like overall it be a decent flick . I could see
0.01:  what a rotten attempt at a comedy . not a single joke land , everyone act annoying and loud , even k
1.00:  launch on netflix be a brave move & I really appreciate be able to binge on episode after episode ,

## Conclusiones

# Lista de comprobación

- [x]  Abriste el notebook
- [ ]  Cargaste y preprocesaste los datos de texto para su vectorización
- [ ]  Transformaste los datos de texto en vectores
- [ ]  Entrenaste y probaste los modelos
- [ ]  Se alcanzó el umbral de la métrica
- [ ]  Colocaste todas las celdas de código en el orden de su ejecución
- [ ]  Puedes ejecutar sin errores todas las celdas de código
- [ ]  Hay conclusiones